### PR TITLE
Support for both esm & commonjs

### PR DESCRIPTION
**Pull request by WiLuX-Source**
I needed this for one of my things and this used CommonJS.
I switched this to ESM to not have problem with other libraries.

### CODE REVIEW

**Comment by sudhakar3697** [comment]
@WiLuX-Source  Thanks for the PR. How do we ensure to support CommonJS imports also?.

**Comment by WiLuX-Source** [comment]
Ok after a bit of work I turned your project into hybrid should i close my pr and make a new one?

**Comment by sudhakar3697** [comment]
> Ok after a bit of work I turned your project into hybrid should i close my pr and make a new one?

Thank you. Pls update this PR itself

**Comment by WiLuX-Source** [comment]
Ok done. If you want you can add readme how to import 2 ways.

**Comment by WiLuX-Source** [comment]
When will you merge this?

**Comment by sudhakar3697** [comment]
> When will you merge this?

I will try it out once and merge it soon.

**Comment by sudhakar3697** [comment]
> When will you merge this?

Merged. Thank you @WiLuX-Source

**Pull request merged**
